import type { EngineInput, FragilityInputs } from "../../nba/probabilityEngine";
import type { NBAArchetype } from "../../nba/archetypes";

const LOW_FRAGILITY: FragilityInputs = {
  normalizedMinutesVariance: 0.1,
  roleUncertainty: 0.05,
  lineupInstability: 0.05,
  blowoutRisk: 0.1,
  usageShock: 0.05,
  lateSeasonChaos: 0.05,
};

const HIGH_FRAGILITY: FragilityInputs = {
  normalizedMinutesVariance: 0.7,
  roleUncertainty: 0.6,
  lineupInstability: 0.65,
  blowoutRisk: 0.55,
  usageShock: 0.4,
  lateSeasonChaos: 0.35,
};

function makeRates(pts: number, reb: number, ast: number, stl = 0.03, blk = 0.02, thr = 0.1) {
  return { points: pts, rebounds: reb, assists: ast, steals: stl, blocks: blk, threes: thr };
}

export interface NBAFixture {
  name: string;
  description: string;
  input: EngineInput;
  options: { familyPenaltyFactor?: number; underBiasCorrectionActive?: boolean };
  expectations: {
    expectedDirection: "OVER" | "UNDER" | "NO_SIGNAL";
    expectedArchetype: NBAArchetype;
    probMin?: number;
    probMax?: number;
    noSignal?: boolean;
    shouldHaveFragilityReasons?: string[];
    isCombo?: boolean;
  };
}

export const NBA_FIXTURES: NBAFixture[] = [
  {
    name: "stable_star_clear_over",
    description: "LeBron-type: 34 min, stable, points over with clear edge",
    input: {
      playerName: "Test Star",
      playerId: 1,
      gameId: "test-1",
      market: "points",
      line: 24.5,
      archetype: "stable_star",
      rateRecent: makeRates(0.85, 0.25, 0.22),
      rateSeason: makeRates(0.80, 0.23, 0.20),
      rateRole: makeRates(0.75, 0.22, 0.18),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.15, 0.08, 0.06),
      varianceRateSeason: makeRates(0.12, 0.07, 0.05),
      varianceRateRole: makeRates(0.10, 0.06, 0.04),
      minutes: { expected: 34, variance: 8 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: LOW_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "OVER",
      expectedArchetype: "stable_star",
      probMin: 0.58,
      probMax: 0.80,
      noSignal: false,
    },
  },
  {
    name: "stable_starter_slight_edge",
    description: "Average starter, slight edge on rebounds — clear separation",
    input: {
      playerName: "Test Starter",
      playerId: 2,
      gameId: "test-2",
      market: "rebounds",
      line: 5.5,
      archetype: "stable_starter",
      rateRecent: makeRates(0.45, 0.24, 0.12),
      rateSeason: makeRates(0.42, 0.22, 0.11),
      rateRole: makeRates(0.40, 0.20, 0.10),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.10, 0.06, 0.04),
      varianceRateSeason: makeRates(0.09, 0.05, 0.03),
      varianceRateRole: makeRates(0.08, 0.05, 0.03),
      minutes: { expected: 32, variance: 12 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: LOW_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "OVER",
      expectedArchetype: "stable_starter",
      probMin: 0.55,
      probMax: 0.80,
      noSignal: false,
    },
  },
  {
    name: "volatile_starter_near_threshold",
    description: "Volatile starter near no-play threshold",
    input: {
      playerName: "Test Volatile",
      playerId: 3,
      gameId: "test-3",
      market: "assists",
      line: 5.5,
      archetype: "volatile_starter",
      rateRecent: makeRates(0.50, 0.18, 0.17),
      rateSeason: makeRates(0.48, 0.17, 0.16),
      rateRole: makeRates(0.45, 0.16, 0.15),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.12, 0.07, 0.06),
      varianceRateSeason: makeRates(0.10, 0.06, 0.05),
      varianceRateRole: makeRates(0.09, 0.05, 0.04),
      minutes: { expected: 28, variance: 35 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: {
        normalizedMinutesVariance: 0.4,
        roleUncertainty: 0.3,
        lineupInstability: 0.2,
        blowoutRisk: 0.2,
        usageShock: 0.15,
        lateSeasonChaos: 0.1,
      },
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "UNDER",
      expectedArchetype: "volatile_starter",
      probMax: 0.70,
    },
  },
  {
    name: "bench_microwave_inflated_recent",
    description: "Bench player with hot recent sample — engine should regress",
    input: {
      playerName: "Test Microwave",
      playerId: 4,
      gameId: "test-4",
      market: "points",
      line: 18.5,
      archetype: "bench_microwave",
      rateRecent: makeRates(1.2, 0.15, 0.08),
      rateSeason: makeRates(0.60, 0.12, 0.06),
      rateRole: makeRates(0.50, 0.10, 0.05),
      recentGameCount: 3,
      varianceRateRecent: makeRates(0.25, 0.08, 0.05),
      varianceRateSeason: makeRates(0.18, 0.06, 0.04),
      varianceRateRole: makeRates(0.15, 0.05, 0.03),
      minutes: { expected: 20, variance: 25 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: {
        normalizedMinutesVariance: 0.4,
        roleUncertainty: 0.3,
        lineupInstability: 0.15,
        blowoutRisk: 0.1,
        usageShock: 0.2,
        lateSeasonChaos: 0.05,
      },
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedArchetype: "bench_microwave",
      expectedDirection: "UNDER",
      probMax: 0.70,
    },
  },
  {
    name: "lineup_impacted_player",
    description: "Recently traded player with lineup disruption",
    input: {
      playerName: "Test Impacted",
      playerId: 5,
      gameId: "test-5",
      market: "points",
      line: 15.5,
      archetype: "lineup_impacted",
      rateRecent: makeRates(0.55, 0.18, 0.10),
      rateSeason: makeRates(0.52, 0.17, 0.09),
      rateRole: makeRates(0.50, 0.16, 0.08),
      recentGameCount: 8,
      varianceRateRecent: makeRates(0.20, 0.08, 0.05),
      varianceRateSeason: makeRates(0.15, 0.07, 0.04),
      varianceRateRole: makeRates(0.12, 0.06, 0.04),
      minutes: { expected: 26, variance: 30 },
      currentStat: 0,
      minutesPlayed: 0,
      // Keep all three structural fragility signals above their reason thresholds
      // (0.5) while staying below the finalizer's fragility-subtraction floor
      // (fragilityScore < 0.40) so the signal isn't suppressed to NO_SIGNAL.
      fragilityInputs: {
        normalizedMinutesVariance: 0.55,
        roleUncertainty: 0.55,
        lineupInstability: 0.55,
        blowoutRisk: 0.0,
        usageShock: 0.0,
        lateSeasonChaos: 0.0,
      },
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedArchetype: "lineup_impacted",
      expectedDirection: "UNDER",
      probMax: 0.64,
      shouldHaveFragilityReasons: ["high_minutes_variance", "role_uncertain", "lineup_unstable"],
    },
  },
  {
    name: "role_uncertain_player",
    description: "Low consistency player with uncertain role",
    input: {
      playerName: "Test Uncertain",
      playerId: 6,
      gameId: "test-6",
      market: "rebounds",
      line: 4.5,
      archetype: "role_uncertain",
      rateRecent: makeRates(0.30, 0.14, 0.05),
      rateSeason: makeRates(0.28, 0.13, 0.04),
      rateRole: makeRates(0.25, 0.12, 0.04),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.15, 0.07, 0.04),
      varianceRateSeason: makeRates(0.12, 0.06, 0.03),
      varianceRateRole: makeRates(0.10, 0.05, 0.03),
      minutes: { expected: 18, variance: 40 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: HIGH_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedArchetype: "role_uncertain",
      expectedDirection: "UNDER",
      probMax: 0.64,
    },
  },
  {
    name: "low_minute_big_player",
    description: "Low-minute center with low usage — classic low_minute_big archetype",
    input: {
      playerName: "Test Big",
      playerId: 11,
      gameId: "test-11",
      market: "rebounds",
      line: 5.5,
      archetype: "low_minute_big",
      rateRecent: makeRates(0.18, 0.22, 0.04),
      rateSeason: makeRates(0.16, 0.20, 0.03),
      rateRole: makeRates(0.14, 0.18, 0.03),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.06, 0.08, 0.02),
      varianceRateSeason: makeRates(0.05, 0.07, 0.02),
      varianceRateRole: makeRates(0.05, 0.06, 0.02),
      minutes: { expected: 18, variance: 30 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: HIGH_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedArchetype: "low_minute_big",
      expectedDirection: "UNDER",
      probMax: 0.72,
    },
  },
  {
    name: "no_signal_insufficient_separation",
    description: "Near-line rates produce insufficient separation — should be NO_SIGNAL",
    input: {
      playerName: "Test NoSig",
      playerId: 12,
      gameId: "test-12",
      market: "rebounds",
      line: 5.5,
      archetype: "stable_starter",
      rateRecent: makeRates(0.42, 0.185, 0.10),
      rateSeason: makeRates(0.41, 0.182, 0.10),
      rateRole: makeRates(0.40, 0.180, 0.10),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.10, 0.06, 0.04),
      varianceRateSeason: makeRates(0.09, 0.05, 0.03),
      varianceRateRole: makeRates(0.08, 0.05, 0.03),
      minutes: { expected: 30, variance: 12 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: HIGH_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "NO_SIGNAL",
      expectedArchetype: "stable_starter",
      noSignal: true,
    },
  },
  {
    name: "combo_prop_pts_reb_ast",
    description: "Combo PRA market for stable star",
    input: {
      playerName: "Test Combo Star",
      playerId: 7,
      gameId: "test-7",
      market: "pts_reb_ast",
      line: 38.5,
      archetype: "stable_star",
      rateRecent: makeRates(0.82, 0.24, 0.22),
      rateSeason: makeRates(0.78, 0.22, 0.20),
      rateRole: makeRates(0.75, 0.21, 0.18),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.14, 0.08, 0.06),
      varianceRateSeason: makeRates(0.12, 0.07, 0.05),
      varianceRateRole: makeRates(0.10, 0.06, 0.04),
      minutes: { expected: 35, variance: 6 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: LOW_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedArchetype: "stable_star",
      expectedDirection: "OVER",
      probMax: 0.74,
      isCombo: true,
    },
  },
  {
    name: "under_side_scenario",
    description: "Player with low rates vs high line — clear UNDER",
    input: {
      playerName: "Test Under",
      playerId: 8,
      gameId: "test-8",
      market: "points",
      line: 22.5,
      archetype: "stable_starter",
      rateRecent: makeRates(0.50, 0.18, 0.12),
      rateSeason: makeRates(0.48, 0.17, 0.11),
      rateRole: makeRates(0.45, 0.16, 0.10),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.12, 0.06, 0.04),
      varianceRateSeason: makeRates(0.10, 0.05, 0.03),
      varianceRateRole: makeRates(0.09, 0.05, 0.03),
      minutes: { expected: 28, variance: 10 },
      currentStat: 0,
      minutesPlayed: 0,
      fragilityInputs: LOW_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "UNDER",
      expectedArchetype: "stable_starter",
      probMin: 0.58,
      probMax: 0.80,
      noSignal: false,
    },
  },
  {
    name: "halftime_valid_2h_play",
    description: "Halftime scenario: star with 12 H1 points, line 24.5",
    input: {
      playerName: "Test HT Star",
      playerId: 9,
      gameId: "test-ht-1",
      market: "points",
      line: 24.5,
      archetype: "stable_star",
      rateRecent: makeRates(0.82, 0.24, 0.20),
      rateSeason: makeRates(0.78, 0.22, 0.18),
      rateRole: makeRates(0.75, 0.20, 0.16),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.14, 0.07, 0.05),
      varianceRateSeason: makeRates(0.12, 0.06, 0.04),
      varianceRateRole: makeRates(0.10, 0.05, 0.04),
      minutes: { expected: 18, variance: 5 },
      currentStat: 12,
      minutesPlayed: 20,
      fragilityInputs: LOW_FRAGILITY,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "OVER",
      expectedArchetype: "stable_star",
      probMin: 0.55,
      probMax: 0.80,
      noSignal: false,
    },
  },
  {
    name: "halftime_no_valid_play",
    description: "Halftime scenario: player already exceeded line",
    input: {
      playerName: "Test HT Already Hit",
      playerId: 10,
      gameId: "test-ht-2",
      market: "points",
      line: 15.5,
      archetype: "stable_starter",
      rateRecent: makeRates(0.60, 0.20, 0.14),
      rateSeason: makeRates(0.55, 0.18, 0.12),
      rateRole: makeRates(0.50, 0.16, 0.10),
      recentGameCount: 10,
      varianceRateRecent: makeRates(0.12, 0.06, 0.04),
      varianceRateSeason: makeRates(0.10, 0.05, 0.03),
      varianceRateRole: makeRates(0.09, 0.05, 0.03),
      // variance=7 gives minutesCertainty=0.669 (≥0.65 elite-gate floor).
      // oddsAgeSec=60 satisfies the freshOdds elite-gate requirement — halftime
      // lines are live, so stale-odds treatment would be wrong here.
      minutes: { expected: 16, variance: 7 },
      currentStat: 18,
      minutesPlayed: 22,
      fragilityInputs: LOW_FRAGILITY,
      oddsAgeSec: 60,
    },
    options: { underBiasCorrectionActive: true },
    expectations: {
      expectedDirection: "OVER",
      expectedArchetype: "stable_starter",
      probMin: 0.80,
      probMax: 1.0,
    },
  },
];
